#
#	MetaCall Library by Parra Studios
#	Docker compose infrastructure for MetaCall.
#
#	Copyright (C) 2016 - 2025 Vicente Eduardo Ferrer Garcia <vic798@gmail.com>
#
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#
#		http://www.apache.org/licenses/LICENSE-2.0
#
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#

version: "3.7"

services:
  deps:
    image: metacall/core:deps
    platform: ${METACALL_PLATFORM}

  dev:
    image: metacall/core:dev
    platform: ${METACALL_PLATFORM}

  runtime:
    image: metacall/core:runtime
    platform: ${METACALL_PLATFORM}

  cli:
    image: metacall/core:cli
    platform: ${METACALL_PLATFORM}
