version: '3.8'

services:
  multiarch-build:
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm/v6
        - linux/arm/v7
        - linux/arm64
