/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface myextensionConstants {
  public final static int MY_EXTENSION_H = myextensionJNI.MY_EXTENSION_H_get();
}
