/*
 *	Preprocessor Library by Parra Studios
 *	A generic header-only preprocessor metaprogramming library.
 *
 *	Copyright (C) 2016 - 2020 Vicente Eduardo Ferrer Garcia <vic798@gmail.com>
 *
 *	Licensed under the Apache License, Version 2.0 (the "License");
 *	you may not use this file except in compliance with the License.
 *	You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 *	Unless required by applicable law or agreed to in writing, software
 *	distributed under the License is distributed on an "AS IS" BASIS,
 *	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *	See the License for the specific language governing permissions and
 *	limitations under the License.
 *
 */

#ifndef PREPROCESSOR_BOOLEAN_H
#define PREPROCESSOR_BOOLEAN_H 1

/* -- Headers -- */

#include <preprocessor/preprocessor_api.h>

#include <preprocessor/preprocessor_complement.h>

#ifdef __cplusplus
extern "C" {
#endif

/* -- Definitions -- */

#define PREPROCESSOR_BOOL_SIZE 256

#define PREPROCESSOR_BOOL_IMPL_0 0
#define PREPROCESSOR_BOOL_IMPL_1 1
#define PREPROCESSOR_BOOL_IMPL_2 1
#define PREPROCESSOR_BOOL_IMPL_3 1
#define PREPROCESSOR_BOOL_IMPL_4 1
#define PREPROCESSOR_BOOL_IMPL_5 1
#define PREPROCESSOR_BOOL_IMPL_6 1
#define PREPROCESSOR_BOOL_IMPL_7 1
#define PREPROCESSOR_BOOL_IMPL_8 1
#define PREPROCESSOR_BOOL_IMPL_9 1
#define PREPROCESSOR_BOOL_IMPL_10 1
#define PREPROCESSOR_BOOL_IMPL_11 1
#define PREPROCESSOR_BOOL_IMPL_12 1
#define PREPROCESSOR_BOOL_IMPL_13 1
#define PREPROCESSOR_BOOL_IMPL_14 1
#define PREPROCESSOR_BOOL_IMPL_15 1
#define PREPROCESSOR_BOOL_IMPL_16 1
#define PREPROCESSOR_BOOL_IMPL_17 1
#define PREPROCESSOR_BOOL_IMPL_18 1
#define PREPROCESSOR_BOOL_IMPL_19 1
#define PREPROCESSOR_BOOL_IMPL_20 1
#define PREPROCESSOR_BOOL_IMPL_21 1
#define PREPROCESSOR_BOOL_IMPL_22 1
#define PREPROCESSOR_BOOL_IMPL_23 1
#define PREPROCESSOR_BOOL_IMPL_24 1
#define PREPROCESSOR_BOOL_IMPL_25 1
#define PREPROCESSOR_BOOL_IMPL_26 1
#define PREPROCESSOR_BOOL_IMPL_27 1
#define PREPROCESSOR_BOOL_IMPL_28 1
#define PREPROCESSOR_BOOL_IMPL_29 1
#define PREPROCESSOR_BOOL_IMPL_30 1
#define PREPROCESSOR_BOOL_IMPL_31 1
#define PREPROCESSOR_BOOL_IMPL_32 1
#define PREPROCESSOR_BOOL_IMPL_33 1
#define PREPROCESSOR_BOOL_IMPL_34 1
#define PREPROCESSOR_BOOL_IMPL_35 1
#define PREPROCESSOR_BOOL_IMPL_36 1
#define PREPROCESSOR_BOOL_IMPL_37 1
#define PREPROCESSOR_BOOL_IMPL_38 1
#define PREPROCESSOR_BOOL_IMPL_39 1
#define PREPROCESSOR_BOOL_IMPL_40 1
#define PREPROCESSOR_BOOL_IMPL_41 1
#define PREPROCESSOR_BOOL_IMPL_42 1
#define PREPROCESSOR_BOOL_IMPL_43 1
#define PREPROCESSOR_BOOL_IMPL_44 1
#define PREPROCESSOR_BOOL_IMPL_45 1
#define PREPROCESSOR_BOOL_IMPL_46 1
#define PREPROCESSOR_BOOL_IMPL_47 1
#define PREPROCESSOR_BOOL_IMPL_48 1
#define PREPROCESSOR_BOOL_IMPL_49 1
#define PREPROCESSOR_BOOL_IMPL_50 1
#define PREPROCESSOR_BOOL_IMPL_51 1
#define PREPROCESSOR_BOOL_IMPL_52 1
#define PREPROCESSOR_BOOL_IMPL_53 1
#define PREPROCESSOR_BOOL_IMPL_54 1
#define PREPROCESSOR_BOOL_IMPL_55 1
#define PREPROCESSOR_BOOL_IMPL_56 1
#define PREPROCESSOR_BOOL_IMPL_57 1
#define PREPROCESSOR_BOOL_IMPL_58 1
#define PREPROCESSOR_BOOL_IMPL_59 1
#define PREPROCESSOR_BOOL_IMPL_60 1
#define PREPROCESSOR_BOOL_IMPL_61 1
#define PREPROCESSOR_BOOL_IMPL_62 1
#define PREPROCESSOR_BOOL_IMPL_63 1
#define PREPROCESSOR_BOOL_IMPL_64 1
#define PREPROCESSOR_BOOL_IMPL_65 1
#define PREPROCESSOR_BOOL_IMPL_66 1
#define PREPROCESSOR_BOOL_IMPL_67 1
#define PREPROCESSOR_BOOL_IMPL_68 1
#define PREPROCESSOR_BOOL_IMPL_69 1
#define PREPROCESSOR_BOOL_IMPL_70 1
#define PREPROCESSOR_BOOL_IMPL_71 1
#define PREPROCESSOR_BOOL_IMPL_72 1
#define PREPROCESSOR_BOOL_IMPL_73 1
#define PREPROCESSOR_BOOL_IMPL_74 1
#define PREPROCESSOR_BOOL_IMPL_75 1
#define PREPROCESSOR_BOOL_IMPL_76 1
#define PREPROCESSOR_BOOL_IMPL_77 1
#define PREPROCESSOR_BOOL_IMPL_78 1
#define PREPROCESSOR_BOOL_IMPL_79 1
#define PREPROCESSOR_BOOL_IMPL_80 1
#define PREPROCESSOR_BOOL_IMPL_81 1
#define PREPROCESSOR_BOOL_IMPL_82 1
#define PREPROCESSOR_BOOL_IMPL_83 1
#define PREPROCESSOR_BOOL_IMPL_84 1
#define PREPROCESSOR_BOOL_IMPL_85 1
#define PREPROCESSOR_BOOL_IMPL_86 1
#define PREPROCESSOR_BOOL_IMPL_87 1
#define PREPROCESSOR_BOOL_IMPL_88 1
#define PREPROCESSOR_BOOL_IMPL_89 1
#define PREPROCESSOR_BOOL_IMPL_90 1
#define PREPROCESSOR_BOOL_IMPL_91 1
#define PREPROCESSOR_BOOL_IMPL_92 1
#define PREPROCESSOR_BOOL_IMPL_93 1
#define PREPROCESSOR_BOOL_IMPL_94 1
#define PREPROCESSOR_BOOL_IMPL_95 1
#define PREPROCESSOR_BOOL_IMPL_96 1
#define PREPROCESSOR_BOOL_IMPL_97 1
#define PREPROCESSOR_BOOL_IMPL_98 1
#define PREPROCESSOR_BOOL_IMPL_99 1
#define PREPROCESSOR_BOOL_IMPL_100 1
#define PREPROCESSOR_BOOL_IMPL_101 1
#define PREPROCESSOR_BOOL_IMPL_102 1
#define PREPROCESSOR_BOOL_IMPL_103 1
#define PREPROCESSOR_BOOL_IMPL_104 1
#define PREPROCESSOR_BOOL_IMPL_105 1
#define PREPROCESSOR_BOOL_IMPL_106 1
#define PREPROCESSOR_BOOL_IMPL_107 1
#define PREPROCESSOR_BOOL_IMPL_108 1
#define PREPROCESSOR_BOOL_IMPL_109 1
#define PREPROCESSOR_BOOL_IMPL_110 1
#define PREPROCESSOR_BOOL_IMPL_111 1
#define PREPROCESSOR_BOOL_IMPL_112 1
#define PREPROCESSOR_BOOL_IMPL_113 1
#define PREPROCESSOR_BOOL_IMPL_114 1
#define PREPROCESSOR_BOOL_IMPL_115 1
#define PREPROCESSOR_BOOL_IMPL_116 1
#define PREPROCESSOR_BOOL_IMPL_117 1
#define PREPROCESSOR_BOOL_IMPL_118 1
#define PREPROCESSOR_BOOL_IMPL_119 1
#define PREPROCESSOR_BOOL_IMPL_120 1
#define PREPROCESSOR_BOOL_IMPL_121 1
#define PREPROCESSOR_BOOL_IMPL_122 1
#define PREPROCESSOR_BOOL_IMPL_123 1
#define PREPROCESSOR_BOOL_IMPL_124 1
#define PREPROCESSOR_BOOL_IMPL_125 1
#define PREPROCESSOR_BOOL_IMPL_126 1
#define PREPROCESSOR_BOOL_IMPL_127 1
#define PREPROCESSOR_BOOL_IMPL_128 1
#define PREPROCESSOR_BOOL_IMPL_129 1
#define PREPROCESSOR_BOOL_IMPL_130 1
#define PREPROCESSOR_BOOL_IMPL_131 1
#define PREPROCESSOR_BOOL_IMPL_132 1
#define PREPROCESSOR_BOOL_IMPL_133 1
#define PREPROCESSOR_BOOL_IMPL_134 1
#define PREPROCESSOR_BOOL_IMPL_135 1
#define PREPROCESSOR_BOOL_IMPL_136 1
#define PREPROCESSOR_BOOL_IMPL_137 1
#define PREPROCESSOR_BOOL_IMPL_138 1
#define PREPROCESSOR_BOOL_IMPL_139 1
#define PREPROCESSOR_BOOL_IMPL_140 1
#define PREPROCESSOR_BOOL_IMPL_141 1
#define PREPROCESSOR_BOOL_IMPL_142 1
#define PREPROCESSOR_BOOL_IMPL_143 1
#define PREPROCESSOR_BOOL_IMPL_144 1
#define PREPROCESSOR_BOOL_IMPL_145 1
#define PREPROCESSOR_BOOL_IMPL_146 1
#define PREPROCESSOR_BOOL_IMPL_147 1
#define PREPROCESSOR_BOOL_IMPL_148 1
#define PREPROCESSOR_BOOL_IMPL_149 1
#define PREPROCESSOR_BOOL_IMPL_150 1
#define PREPROCESSOR_BOOL_IMPL_151 1
#define PREPROCESSOR_BOOL_IMPL_152 1
#define PREPROCESSOR_BOOL_IMPL_153 1
#define PREPROCESSOR_BOOL_IMPL_154 1
#define PREPROCESSOR_BOOL_IMPL_155 1
#define PREPROCESSOR_BOOL_IMPL_156 1
#define PREPROCESSOR_BOOL_IMPL_157 1
#define PREPROCESSOR_BOOL_IMPL_158 1
#define PREPROCESSOR_BOOL_IMPL_159 1
#define PREPROCESSOR_BOOL_IMPL_160 1
#define PREPROCESSOR_BOOL_IMPL_161 1
#define PREPROCESSOR_BOOL_IMPL_162 1
#define PREPROCESSOR_BOOL_IMPL_163 1
#define PREPROCESSOR_BOOL_IMPL_164 1
#define PREPROCESSOR_BOOL_IMPL_165 1
#define PREPROCESSOR_BOOL_IMPL_166 1
#define PREPROCESSOR_BOOL_IMPL_167 1
#define PREPROCESSOR_BOOL_IMPL_168 1
#define PREPROCESSOR_BOOL_IMPL_169 1
#define PREPROCESSOR_BOOL_IMPL_170 1
#define PREPROCESSOR_BOOL_IMPL_171 1
#define PREPROCESSOR_BOOL_IMPL_172 1
#define PREPROCESSOR_BOOL_IMPL_173 1
#define PREPROCESSOR_BOOL_IMPL_174 1
#define PREPROCESSOR_BOOL_IMPL_175 1
#define PREPROCESSOR_BOOL_IMPL_176 1
#define PREPROCESSOR_BOOL_IMPL_177 1
#define PREPROCESSOR_BOOL_IMPL_178 1
#define PREPROCESSOR_BOOL_IMPL_179 1
#define PREPROCESSOR_BOOL_IMPL_180 1
#define PREPROCESSOR_BOOL_IMPL_181 1
#define PREPROCESSOR_BOOL_IMPL_182 1
#define PREPROCESSOR_BOOL_IMPL_183 1
#define PREPROCESSOR_BOOL_IMPL_184 1
#define PREPROCESSOR_BOOL_IMPL_185 1
#define PREPROCESSOR_BOOL_IMPL_186 1
#define PREPROCESSOR_BOOL_IMPL_187 1
#define PREPROCESSOR_BOOL_IMPL_188 1
#define PREPROCESSOR_BOOL_IMPL_189 1
#define PREPROCESSOR_BOOL_IMPL_190 1
#define PREPROCESSOR_BOOL_IMPL_191 1
#define PREPROCESSOR_BOOL_IMPL_192 1
#define PREPROCESSOR_BOOL_IMPL_193 1
#define PREPROCESSOR_BOOL_IMPL_194 1
#define PREPROCESSOR_BOOL_IMPL_195 1
#define PREPROCESSOR_BOOL_IMPL_196 1
#define PREPROCESSOR_BOOL_IMPL_197 1
#define PREPROCESSOR_BOOL_IMPL_198 1
#define PREPROCESSOR_BOOL_IMPL_199 1
#define PREPROCESSOR_BOOL_IMPL_200 1
#define PREPROCESSOR_BOOL_IMPL_201 1
#define PREPROCESSOR_BOOL_IMPL_202 1
#define PREPROCESSOR_BOOL_IMPL_203 1
#define PREPROCESSOR_BOOL_IMPL_204 1
#define PREPROCESSOR_BOOL_IMPL_205 1
#define PREPROCESSOR_BOOL_IMPL_206 1
#define PREPROCESSOR_BOOL_IMPL_207 1
#define PREPROCESSOR_BOOL_IMPL_208 1
#define PREPROCESSOR_BOOL_IMPL_209 1
#define PREPROCESSOR_BOOL_IMPL_210 1
#define PREPROCESSOR_BOOL_IMPL_211 1
#define PREPROCESSOR_BOOL_IMPL_212 1
#define PREPROCESSOR_BOOL_IMPL_213 1
#define PREPROCESSOR_BOOL_IMPL_214 1
#define PREPROCESSOR_BOOL_IMPL_215 1
#define PREPROCESSOR_BOOL_IMPL_216 1
#define PREPROCESSOR_BOOL_IMPL_217 1
#define PREPROCESSOR_BOOL_IMPL_218 1
#define PREPROCESSOR_BOOL_IMPL_219 1
#define PREPROCESSOR_BOOL_IMPL_220 1
#define PREPROCESSOR_BOOL_IMPL_221 1
#define PREPROCESSOR_BOOL_IMPL_222 1
#define PREPROCESSOR_BOOL_IMPL_223 1
#define PREPROCESSOR_BOOL_IMPL_224 1
#define PREPROCESSOR_BOOL_IMPL_225 1
#define PREPROCESSOR_BOOL_IMPL_226 1
#define PREPROCESSOR_BOOL_IMPL_227 1
#define PREPROCESSOR_BOOL_IMPL_228 1
#define PREPROCESSOR_BOOL_IMPL_229 1
#define PREPROCESSOR_BOOL_IMPL_230 1
#define PREPROCESSOR_BOOL_IMPL_231 1
#define PREPROCESSOR_BOOL_IMPL_232 1
#define PREPROCESSOR_BOOL_IMPL_233 1
#define PREPROCESSOR_BOOL_IMPL_234 1
#define PREPROCESSOR_BOOL_IMPL_235 1
#define PREPROCESSOR_BOOL_IMPL_236 1
#define PREPROCESSOR_BOOL_IMPL_237 1
#define PREPROCESSOR_BOOL_IMPL_238 1
#define PREPROCESSOR_BOOL_IMPL_239 1
#define PREPROCESSOR_BOOL_IMPL_240 1
#define PREPROCESSOR_BOOL_IMPL_241 1
#define PREPROCESSOR_BOOL_IMPL_242 1
#define PREPROCESSOR_BOOL_IMPL_243 1
#define PREPROCESSOR_BOOL_IMPL_244 1
#define PREPROCESSOR_BOOL_IMPL_245 1
#define PREPROCESSOR_BOOL_IMPL_246 1
#define PREPROCESSOR_BOOL_IMPL_247 1
#define PREPROCESSOR_BOOL_IMPL_248 1
#define PREPROCESSOR_BOOL_IMPL_249 1
#define PREPROCESSOR_BOOL_IMPL_250 1
#define PREPROCESSOR_BOOL_IMPL_251 1
#define PREPROCESSOR_BOOL_IMPL_252 1
#define PREPROCESSOR_BOOL_IMPL_253 1
#define PREPROCESSOR_BOOL_IMPL_254 1
#define PREPROCESSOR_BOOL_IMPL_255 1
#define PREPROCESSOR_BOOL_IMPL_256 1

/* -- Macros -- */

#define PREPROCESSOR_BOOL_IMPL(expr) PREPROCESSOR_BOOL_IMPL_ ## expr

#if defined(__MWERKS__)
#	define PREPROCESSOR_BOOL_TOKEN(expr) PREPROCESSOR_BOOL_IMPL ## expr
#	define PREPROCESSOR_BOOL(expr) PREPROCESSOR_BOOL_TOKEN((expr))
#else
#	define PREPROCESSOR_BOOL(expr) PREPROCESSOR_BOOL_IMPL(expr)
#endif

#if defined(__EDG__) || defined(__EDG_VERSION__)
#	define PREPROCESSOR_NOT(expr) PREPROCESSOR_NOT_IMPL(expr)
#	define PREPROCESSOR_NOT_IMPL(expr) PREPROCESSOR_COMPL(PREPROCESSOR_BOOL(expr))
#else
#	define PREPROCESSOR_NOT(expr) PREPROCESSOR_COMPL(PREPROCESSOR_BOOL(expr))
#endif

#ifdef __cplusplus
}
#endif

#endif /* PREPROCESSOR_BOOLEAN_H */
