name: FreeBSD Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: FreeBSD Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cpa.sh {0}
    strategy:
      fail-fast: false
      matrix:
        # TODO: Implement more architectures and versions matrix
        # TODO: Implement OpenBSD, Haiku, OmniOS
        build: [release, relwithdebinfo]
        arch: [x86-64]
        include:
          # c and wasm loaders are not supported on arm64 FreeBSD;
          - arch: x86-64
            extra-loaders: "c wasm"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start FreeBSD VM
        uses: cross-platform-actions/action@v1.1.0
        with:
          operating_system: freebsd
          version: "14.2"
          architecture: ${{ matrix.arch }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
