name: FreeBSD Test

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  freebsd-test:
    name: FreeBSD Test
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        build: [debug, release]
        version: [14.3]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests in FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.version }}
          usesh: true
          run: |
            set -eux
            
            sh ./tools/metacall-environment.sh base python backtrace
            
            sh ./tools/metacall-configure.sh
            
            gmake -j$(sysctl -n hw.ncpu)
            gmake install

            sh ./tools/metacall-build.sh
